### ISSUE TITLE
lts 8.11

### ISSUE THREAD

**Issue by alexanderkjeldaas** [matchwood/ghcjs-stack-dist#1]
should probably figure out how to do this myself, but if it's possible, could you create an lts 8.11 version?

**Comment by matchwood** [comment]
I'll look into this in the next day or two. Also, if you are interested in contributing then I would be happy to give you some guidance!

**Comment by matchwood** [comment]
I have added a version for 8.1, but please see the note about aeson in the readme before using it! Let me know how you get on.
