### ISSUE TITLE
keep old tarballs?

### ISSUE THREAD

**Issue by fisx** [matchwood/ghcjs-stack-dist#2]
I just realized that you killed the old tar balls that I've been reyling on (which is admittedly my own mistake, so I'm not complaining!  :-)

I am going to fork this repo now to be safe in the future, but just for the record I would suggest you keep the old images around a bit longer.

Or was there a reason why they should be immediately updated?

Anyway, thanks for this, it's much appreciated!

**Comment by matchwood** [comment]
Ah sorry about that, no need to fork the repo though - you should be able to use the commit history for them eg:
https://github.com/matchwood/ghcjs-stack-dist/blob/e974993662a21d8543709b9b2a04c422d9abf3ca/ghcjs-0.2.1.9008000.tar.gz?raw=true

The reason I didn't keep them in master is that the aeson included in those versions was broken when compiled to js and aeson is a core package in ghcjs. I considered it better to break dependencies like yours so at least anyone using them would be aware of the problem. If you don't need aeson, or any package relying on aeson, then you may be ok, but on the whole I would recommend updating to the lts-8.11 release (with the caveats mentioned in the note on aeson).

I was initially planning to put together replacement releases for 8.0 and 8.5, but it takes a fair amount of (cpu) time to do each one, and I figure that anyone using 8.0 or 8.5 should be able to upgrade to 8.11 with minimal code changes, if any.

**Comment by fisx** [comment]
Yeah, I'm optimistic about the upgrade, but still building...

Thanks for the background info, I agree that's a good reason to take down the old tarballs.

cheers!

**Comment by matchwood** [comment]
Great, let me know if you encounter any problems.
