### ISSUE TITLE
lts-8.12

### ISSUE THREAD

**Issue by pmlodawski** [matchwood/ghcjs-stack-dist#3]
Are there any chances to see lts-8.12? 
I have issues with `foundation` package on Windows which was fixed in lts-8.12 (see [ haskell-foundation/foundation#238 (comment)](https://github.com/haskell-foundation/foundation/issues/238#issuecomment-295846373)

Thanks!

**Comment by pmlodawski** [comment]
Now I see that ghc 8 is not supported yet on Windows (https://github.com/ghcjs/ghcjs/issues/548), so updating to lts-8.12 won't help

**Comment by matchwood** [comment]
Well if you wanted to try you can always bump that one package in your stack.yaml without updating to lts-8.12? But in any case I'll close this issue for now as your specific issue does seem to be blocked by lack of windows support for ghcjs.
